[project]
name = "wildfire-ai"
version = "0.1.0"
description = "AI-powered wildfire monitoring platform using computer vision, geospatial analytics and machine learning."
readme = "README.md"
authors = [
    { name = "Mateo Pozo", email = "mateopgarcia24@gmail.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = []

[project.scripts]
wildfire-ai = "wildfire_ai:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
